replicate-jenkins:
 image: dmuchuari/replicate-jenkins:latest
 environment: 
       JENKINS_OPTS: "--prefix=/jenkins"
 ports: 
       - "9999:8080"
 entrypoint: /bin/sh -c "/bin/bash -c \"$${@}\""
 command: |
      /bin/bash -c "chmod 777 /etc/jenkins_jobs/script-to-execute.sh && ./etc/jenkins_jobs/script-to-execute.sh"
